name: Node.js CI

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  log-context:
    runs-on: ubuntu-latest
    steps:
      # Dump all contexts
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        run: echo "$MATRIX_CONTEXT"

  get-test-definition-files:
    name: Get Test Definition Files
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.get-test-definition-files.outputs.result }}
    steps:
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'

      - name: Checkout open-install-library Repo
        uses: actions/checkout@v2
        with:
          repository: newrelic/open-install-library
          path: ${{ github.workspace }}/oil

      - name: Checkout sandbox repo
        uses: actions/checkout@v2
        with:
          path: derp

      - name: Get Test Definition Files
        id: get-test-definition-files
        working-directory: ${{ github.workspace }}/derp/.github/scripts
        run: node findTestDefinitionFiles.js
  test-deploy-recipe:
    name: ${{ matrix.testDisplayName }}
    needs: [ get-test-definition-files ]
    if: ${{ fromJSON(needs.get-test-definition-files.outputs.matrix).include[0] }} # Avoids empty matrix validation error
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJSON(needs.get-test-definition-files.outputs.matrix) }}
      fail-fast: false
    env:
      MATRIX: ${{ toJSON(matrix) }}
    steps:
      - name: Install dependencies for test scripts
        working-directory: ${{ github.workspace }}/derp/.github/scripts
        run: npm install

      - name: Run test scripts
        working-directory: ${{ github.workspace }}/derp/.github/scripts
        run: node main.js
        env:
          TEST_DEFINITION_URL: https://raw.githubusercontent.com/newrelic/open-install-library/main/test/definitions/${{ matrix.testDefinitionFile }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          SQS_URL: ${{ secrets.SQS_URL }}
          DYNAMO_TABLE: ${{ secrets.DYNAMO_TABLE }}

