name: Node.js CI

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  log-context:
    runs-on: ubuntu-latest
    steps:
      # Dump all contexts
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        run: echo "$MATRIX_CONTEXT"

  get-test-files:
    name: Get open-install-library test files
    runs-on: ubuntu-latest
    outputs:
      infra-agent-files: ${{ steps.find-infra-agent-files.outputs.files }}
      logging-files: ${{ steps.find-logging-files.outputs.files }}
      ohi-files: ${{ steps.find-ohi-files.outputs.files }}
    steps:
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'
      - name: Checkout open-install-library Repo
        uses: actions/checkout@v2
        with:
          repository: newrelic/open-install-library
          path: ${{ github.workspace }}/oil
      - name: Checkout sandbox repo
        uses: actions/checkout@v2
        with:
          path: derp
      - name: Get Infra-Agent Test Files
        id: find-infra-agent-files
        working-directory: ${{ github.workspace }}/derp/.github/scripts
        run: echo "files=$(node findTestDefinitionFiles.js /test/definitions/infra-agent )" >> $GITHUB_OUTPUT
      - name: Get Logging Test Files
        id: find-logging-files
        working-directory: ${{ github.workspace }}/derp/.github/scripts
        run: echo "files=$(node findTestDefinitionFiles.js /test/definitions/logging )" >> $GITHUB_OUTPUT
      - name: Get OHI Test Files
        id: find-ohi-files
        working-directory: ${{ github.workspace }}/derp/.github/scripts
        run: echo "files=$(node findTestDefinitionFiles.js /test/definitions/ohi )" >> $GITHUB_OUTPUT


  run-infra-agent-tests:
    name: ${{ matrix.testDisplayName }}
    needs: [ get-test-files ]
    if: ${{ fromJSON(needs.get-test-files.outputs.infra-agent-files).include[0] }} # Avoids empty matrix validation error
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.get-test-files.outputs.infra-agent-files) }}
      fail-fast: false
    env:
      MATRIX: ${{ toJSON(matrix) }}
    steps:
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'

      - name: checkout sandbox repo
        uses: actions/checkout@v2
        with:
          path: derp

      - name: install dependencies
        working-directory: ${{ github.workspace }}/derp/.github/scripts
        run: npm install

      - name: run test
        working-directory: ${{ github.workspace }}/derp/.github/scripts
        run: node main.js
        env:
          TEST_DEFINITION_URL: https://raw.githubusercontent.com/newrelic/open-install-library/main${{ matrix.testDefinitionSuffix }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          SQS_URL: ${{ secrets.SQS_URL }}
          DYNAMO_TABLE: ${{ secrets.DYNAMO_TABLE }}

#  run-logging-tests:
#    name: ${{ matrix.testDisplayName }}
#    needs: [ get-test-files ]
#    if: ${{ fromJSON(needs.get-test-files.outputs.logging-files).include[0] }} # Avoids empty matrix validation error
#    runs-on: ubuntu-latest
#    strategy:
#      matrix: ${{ fromJson(needs.get-test-files.outputs.logging-files) }}
#      fail-fast: false
#    env:
#      MATRIX: ${{ toJSON(matrix) }}
#    steps:
#      - name: Use Node.js
#        uses: actions/setup-node@v1
#        with:
#          node-version: '18.x'
#
#      - name: checkout sandbox repo
#        uses: actions/checkout@v2
#        with:
#          path: derp
#
#      - name: install dependencies
#        working-directory: ${{ github.workspace }}/derp/.github/scripts
#        run: npm install
#
#      - name: run test
#        working-directory: ${{ github.workspace }}/derp/.github/scripts
#        run: node main.js
#        env:
#          TEST_DEFINITION_URL: https://raw.githubusercontent.com/newrelic/open-install-library/main${{ matrix.testDefinitionSuffix }}
#          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#          AWS_REGION: ${{ secrets.AWS_REGION }}
#          SQS_URL: ${{ secrets.SQS_URL }}
#          DYNAMO_TABLE: ${{ secrets.DYNAMO_TABLE }}
#
#  run-ohi-tests:
#    name: ${{ matrix.testDisplayName }}
#    needs: [ get-test-files ]
#    if: ${{ fromJSON(needs.get-test-files.outputs.ohi-files).include[0] }} # Avoids empty matrix validation error
#    runs-on: ubuntu-latest
#    strategy:
#      matrix: ${{ fromJson(needs.get-test-files.outputs.ohi-files) }}
#      fail-fast: false
#    env:
#      MATRIX: ${{ toJSON(matrix) }}
#    steps:
#      - name: Use Node.js
#        uses: actions/setup-node@v1
#        with:
#          node-version: '18.x'
#
#      - name: checkout sandbox repo
#        uses: actions/checkout@v2
#        with:
#          path: derp
#
#      - name: install dependencies
#        working-directory: ${{ github.workspace }}/derp/.github/scripts
#        run: npm install
#
#      - name: run test
#        working-directory: ${{ github.workspace }}/derp/.github/scripts
#        run: node main.js
#        env:
#          TEST_DEFINITION_URL: https://raw.githubusercontent.com/newrelic/open-install-library/main${{ matrix.testDefinitionSuffix }}
#          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#          AWS_REGION: ${{ secrets.AWS_REGION }}
#          SQS_URL: ${{ secrets.SQS_URL }}
#          DYNAMO_TABLE: ${{ secrets.DYNAMO_TABLE }}
